config/routes.rb
Project::Application.routes.draw do
  
  resources :dashboards

  root :to => redirect('/dashboards')


  get '/login' , to: 'sessions#login'
  post '/login' , to: 'sessions#create'
  post '/logout' , to: 'sessions#destroy'
  get '/logout' , to: 'sessions#destroy'

  get '/schedule', :controller => 'employees', :action => 'show'

end

app/models/actual.rb
class Actual < ActiveRecord::Base
	belongs_to :plan
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :user
	has_many :actuals

	validates :user_id, :presence=>true
	validates :time_in, :presence=>true
	validates :time_out, :presence=>true
	validates :date, :presence=>true
	validates :OT, :presence=>true
end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password
	has_many :plans
	has_many :actuals

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authorized
	helper_method :current_user
	helper_method :logged_in?

	
	def current_user    
		User.find_by(id: session[:user_id])
	end

	def logged_in?
      	!current_user.nil?
    end

    def authorized   
    	redirect_to login_path unless logged_in?
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def index
	end

	def edit
		@dep = params[:id]
		@users = User.where(:department1 => @dep)
		@employee = @users.select{|user| user.position=="employee"}
		# click to assign shift
		if (params.key?('ass_button'))
			@calender = params[:emp][:date]
			# list of user id (tick checkbox)
			@uID_list = params[:select_user]
			new_time_out = (@calender+' '+(params[:time].split[2])).to_time
			new_time_in = (@calender+' '+(params[:time].split[0])).to_time
			tomorrow = ["00:00","00:30","01:00","01:30","02:00","02:30","03:00","03:30","04:00","04:30","05:00","05:30","06:00","06:30","07:00","07:30","08:00","08:30"]
			if tomorrow.include?(params[:time].split[2])
				new_time_out += (3600*24)
			end
			if @uID_list
				@uID_list.each do |uID|
					@all_user_plan = Plan.find_by_user_id(uID) # get database
					if @all_user_plan != nil
						# insert each data to Plan database
						if (@all_user_plan.time_in > new_time_out && @all_user_plan.time_in > new_time_in) || (@all_user_plan.time_out < new_time_in && @all_user_plan.time_out < new_time_out)
							@assign = Plan.create(time_plan)
							user = User.find(uID.to_i)
							user.plans << @assign
							if @assign.save
								#if creation is successful, show up 'successful' message
								flash[:notice] = "Assign shift successfully"
								#redirect_to edit_dashboard_path(@dep)
							else
								render 'edit'
							end
						# update each data to Plan database		
						elsif (@all_user_plan.time_in < new_time_out && @all_user_plan.time_in > new_time_in) || (@all_user_plan.time_out > new_time_in && @all_user_plan.time_out < new_time_out)
							if @all_user_plan.update_attributes(time_plan) 
						    	flash[:notice] = "Update shift successfully"
						    	#redirect_to edit_dashboard_path(@dep)
						    else
						    	render 'edit'
						    end
						else
							flash[:notice] = "Can't assign shift"
						end
					# create data Plan if don't have anything in database
					else
						@assign = Plan.create(time_plan)
						user = User.find(uID.to_i)
						user.plans << @assign
						if @assign.save
							#if creation is successful, show up 'successful' message
							flash[:notice] = "Assign shift successfully"
							#redirect_to edit_dashboard_path(@dep)
						else
							render 'edit'
						end
					end
				end
				redirect_to edit_dashboard_path(@dep)
			end
		end

		# time
		@all_time = ["00:00 - 09:00","00:30 - 09:30","01:00 - 10:00","01:30 - 10:30","02:00 - 11:00","02:30 - 11:30",
					"03:00 - 12:00","03:30 - 12:30","04:00 - 13:00","04:30 - 13:30","05:00 - 14:00","05:30 - 14:30",
					"06:00 - 15:00","06:30 - 15:30","07:00 - 16:00","07:30 - 16:30","08:00 - 17:00","08:30 - 17:30",
					"09:00 - 18:00","09:30 - 18:30","10:00 - 19:00","10:30 - 19:30","11:00 - 20:00","11:30 - 20:30",
					"12:00 - 21:00","12:30 - 21:30","13:00 - 22:00","13:30 - 22:30","14:00 - 23:00","14:30 - 23:30",
					"15:00 - 00:00","15:30 - 00:30","16:00 - 01:00","16:30 - 01:30","17:00 - 02:00","17:30 - 02:30",
					"18:00 - 03:00","18:30 - 03:30","19:00 - 04:00","19:30 - 04:30","20:00 - 05:00","20:30 - 05:30",
					"21:00 - 06:00","21:30 - 06:30","22:00 - 07:00","22:30 - 07:30","23:00 - 08:00","23:30 - 08:30"]

		@default_select = "00:00 - 09:00"

		@status = false
		
		if (params.key?("choose"))
			@calender = params[:emp][:date]
			@status = true
		end

	end

	def show
		@department_name = params[:id]
		@all_workers = User.where(:position => 'employee', :department1 => @department_name)
	
		@all_time = ["all","00:00 - 09:00","00:30 - 09:30","01:00 - 10:00","01:30 - 10:30","02:00 - 11:00","02:30 - 11:30",
					"03:00 - 12:00","03:30 - 12:30","04:00 - 13:00","04:30 - 13:30","05:00 - 14:00","05:30 - 14:30",
					"06:00 - 15:00","06:30 - 15:30","07:00 - 16:00","07:30 - 16:30","08:00 - 17:00","08:30 - 17:30",
					"09:00 - 18:00","09:30 - 18:30","10:00 - 19:00","10:30 - 19:30","11:00 - 20:00","11:30 - 20:30",
					"12:00 - 21:00","12:30 - 21:30","13:00 - 22:00","13:30 - 22:30","14:00 - 23:00","14:30 - 23:30",
					"15:00 - 00:00","15:30 - 00:30","16:00 - 01:00","16:30 - 01:30","17:00 - 02:00","17:30 - 02:30",
					"18:00 - 03:00","18:30 - 03:30","19:00 - 04:00","19:30 - 04:30","20:00 - 05:00","20:30 - 05:30",
					"21:00 - 06:00","21:30 - 06:30","22:00 - 07:00","22:30 - 07:30","23:00 - 08:00","23:30 - 08:30"]

		@select = "all" 

		@status = false

		if (params.key?("choose"))
			@select = params[:time_in]
			@calender = params[:date_work].values[0]
			@t_in = (@calender + ' '+ @select[0..4]).to_time
			@status = true
		end

	end

	def time_plan
		data = params.require(:emp).permit(:date, :OT)
		day = params[:emp][:date]
		str_time_in = params[:time].split[0]
		str_time_out = params[:time].split[2]
		data[:date] = day.to_time
		data[:time_in] = (day+' '+str_time_in).to_time
		check_time_out = (day+' '+str_time_out).to_time
		tomorrow = ["00:00","00:30","01:00","01:30","02:00","02:30","03:00","03:30","04:00","04:30","05:00","05:30","06:00","06:30","07:00","07:30","08:00","08:30"]
		if tomorrow.include? str_time_out
			data[:time_out] = check_time_out + (3600*24)
		else
			data[:time_out] = check_time_out
		end
		if params[:emp][:OT] == ""
			data[:OT] = 0
		end
		return data
	end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def show
		@time = Time.current
		day = Time.current.strftime("%Y-%m-%d")
		@date = day.to_time 

		userid = current_user.id
		user = User.find(userid)
		plan = Plan.find_by(:user_id => userid , :date => @date)
		@all_plans = Plan.where(:user_id => userid).order("date DESC")

		check_actual = Actual.find_by(:date => @date , :user_id => userid)

		if (params.key?("save_in")) && plan != nil
			if check_actual == nil 
				user_actual =  Actual.create(:date => @date , :time_in => @time )
				user.actuals << user_actual
				plan.actuals << user_actual
				flash[:notice] = "check in success"
			elsif check_actual.time_in != nil
				flash[:notice] = "You have check in before !"
			end	
			redirect_to schedule_path
		elsif (params.key?("save_in"))
			flash[:notice] = "You don't have any plan !"

		end

		if (params.key?("save_out")) && plan != nil
			if check_actual != nil && check_actual.time_out == nil
				check_actual.update(:time_out => @time )
				act_out = check_actual.time_out
				plan_out = plan.time_out
				@ot = (act_out-plan_out+(12*3600))/(60*60)
				check_actual.update(:OT => @ot )
				flash[:notice] = "check out success"
			else
				flash[:notice] = "You have check out before !"
			end	
			redirect_to schedule_path
		elsif (params.key?("save_out"))
			flash[:notice] = "You don't have any plan !"
		end
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_action :authorized

	def create
		@user = User.find_by(username: params[:username])

		if @user && @user.authenticate(params[:password])
	  		session[:user_id] = @user.id
	  		if @user.position == "leader"
	  			redirect_to dashboards_path
	  		else 
	  			redirect_to schedule_path
	  		end
		else
	  		message = "Oop Sorry ! Make sure your username and password are correct !!"
	  		redirect_to login_path , notice: message
		end
  	end

  	def destroy
		session.delete(:user_id)
		flash[:notice] = 'Logged out successfully.'
		redirect_to login_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in?
		!!session[:user_id]
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if !!session[:user_id]
	end
	
end

app/views/dashboards/_dashboard_form.html.erb
<div class="item-container">
    <div class="title-department">
    <%= link_to current_user.department1 ,  dashboard_path(current_user.department1) %>
    </div>
    <div class="actual-btn">
    <%= link_to 'actual',  dashboard_path(current_user.department1)  %>
    </div>
    <div class="plan-btn">
    <%= link_to 'plan',  edit_dashboard_path(current_user.department1)  %>
    </div>
</div>
<div class="item-container">
    <div class="title-department">
    <%= current_user.department2 %>
    </div>
    <div class="actual-btn">
    <%= link_to 'actual2',  dashboard_path(current_user.department2)  %>
    </div>
    <div class="plan-btn">
    <%= link_to 'plan2',  edit_dashboard_path(current_user.department2)  %>
    </div>
</div>
<div class="item-container">
    <div class="title-department">
    <%= current_user.department3 %>
    </div>
    <div class="actual-btn">
    <%= link_to 'actual3',  dashboard_path(current_user.department3)  %>
    </div>
    <div class="plan-btn">
    <%= link_to 'plan3',  edit_dashboard_path(current_user.department3)  %>
    </div>
</div>

app/views/dashboards/edit.html.erb
<h1 class="headerer">
  <%= link_to 'Assign shift', root_path %>
</h1>
<body>
  <h2>Plan แผนก <%= @dep %></h2>
  
  <%= form_tag(edit_dashboard_path(@dep), method: 'get') do %>
    <% today = Time.current.strftime("%Y-%m-%d") %>
    Date
    <% if @status == true %>
      <%= date_field(:emp, :date, :value => @calender, :min => today ) %>
    <% else %>
      <%= date_field(:emp, :date, :value => today, :min => today ) %>
    <% end %>
    <%= submit_tag 'select' , :name => "choose"  %><br>
    Time <%= select_tag :time, options_for_select(@all_time, @default_select)  %>
    OT <%= text_field :emp, :OT %>
    <%= submit_tag "Submit" , :name=>'ass_button' %>

    <table>
      <tr>
        <th><%= check_box_tag :check_all %></th>
        <th>ชื่อ-นามสกุล</th>
        <th>เวลาเข้างาน</th>
        <th>เวลาออกงาน</th>
        <th>OT Plane</th>
      </tr>
      <% @employee.each do |users| %>
      <% if @status == false %>
          <% user_plan = users.plans.find_by_date(today) %>
      <% elsif @status == true %>
          <% user_plan = users.plans.find_by_date(@calender) %>
      <% end %>
      <tr>
        <td><%= check_box_tag "select_user[]", users.id %></td>
        <td><%= users.name.to_s+" "+users.surname.to_s %></td>
        <% if user_plan != nil  %>
          <% if user_plan.date != nil  %>
            <td><%= (user_plan.time_in + (3600*12)).strftime('%H:%M:%S') %></td>
            <td><%= (user_plan.time_out + (3600*12)).strftime('%H:%M:%S') %></td>
            <td><%= user_plan.OT.to_s %></td>
          <% else %>
            <td> - </td>
            <td> - </td>
            <td> - </td>
          <% end %>
        <% else %>
          <td> - </td>
          <td> - </td>
          <td> - </td>
        <% end %>
      </tr>
      <% end %>
    </table>
  <% end %>

</body>

<%= javascript_pack_tag 'select_all', 'data-turbolinks-track':'reload' %>

app/views/dashboards/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    
  </head>
  

  <body>
    <h1>Dash Board </h1>
    <h2>จัดการแผนก</h2>
    <div class="dashboard-cotainer">
      <%= render :partial=>'dashboard_form' %>  
    </div>
  </body>
</html>

app/views/dashboards/show.html.erb
<h1 class="title">
	<%= "แผนก : " + @department_name %>
</h1>

<div id="pick_time">
	<div class="item">
<%= link_to 'Plan', edit_dashboard_path(@department_name), :class =>"plan-btn-show" %><br>
	</div>
<% day = Time.current.strftime("%Y-%m-%d") %>
<% date = day.to_time %>
	<%= form_tag dashboard_path(@department_name) , :method => :get do %>
		<div class="form-container">
		<div class="item">
			<a>กะการทำงาน :</a>
			<%= select_tag 'time_in', options_for_select(@all_time, @select)  %>
		</div>
		<div class="item">
		วันที่ทำงาน :
		<% if @status == true %>
			<%= date_field("date_work", "date_work" , :value => @calender ) %>
		<% else %>
			<%= date_field("date_work", "date_work" , :value => day ) %>
		<% end %>
		</div>
		<div class="item">
		<%= submit_tag 'select' , :name => "choose"  %>
		</div>
		</div>
	<% end %>

<% num_now = 0 %>
<% num_plan = 0 %>

<% @all_workers.each do |num| %>

	<% actual = num.actuals.find_by_date(@calender) %>
	<% if actual != nil %>
		<% if @select == "all"  %>
			<% if actual.time_in != nil && actual.time_out == nil %>
				<% num_now += 1 %>
			<% end %>
		<% else %>
			<% plan = num.plans.find_by(:date => @calender , :time_in => @t_in) %>
			<% if actual.time_in != nil && actual.time_out == nil && plan != nil %>
				<% num_now += 1 %>
			<% end %>

		<% end %>
	<% end %>



	<% if @select == "all"  %>
		<% if @status == false %>
			<% plan = num.plans.find_by_date(date) %>
		<% elsif @status == true %>
			<% plan = num.plans.find_by_date(@calender) %>
		<% end %>

		<% if plan != nil %>
			<% num_plan += 1 %>
		<% end %>

	<% else %>
		<% plan = num.plans.find_by(:date => @calender , :time_in => @t_in) %>
		<% if plan != nil %>
			<% num_plan += 1 %>
		<% end %>

	<% end %>


<% end %>
<div class="item">
<%= "จำนวนคน : "+ num_now.to_s + " / " + num_plan.to_s %>
</div>
</div>

<div class="table-container">
<table >
	<thead>
		<tr>
			<th> ชื่อ-นามสกุล </th>
			<th> เวลาเข้างาน </th>
			<th> เวลาออกงาน </th>
			<th> OT </th>
		</tr>
	</thead>
	<tbody>
		<% @all_workers.each do |worker| %>
			<tr>

				<% if @status == false %>
					<% worker_all_actuals = worker.actuals.find_by_date(date) %>
				<% elsif @status == true %>
					<% worker_all_actuals = worker.actuals.find_by_date(@calender) %>
				<% end %>

				<% if @select == "all"  %>
					<% if @status == false %>
						<% worker_all_plan = worker.plans.find_by_date(date) %>
					<% elsif @status == true %>
						<% worker_all_plan = worker.plans.find_by_date(@calender) %>
					<% end %>

				<% else %>
					<% worker_all_plan = worker.plans.find_by(:date => @calender , :time_in => @t_in) %>
				<% end %>

				<% if worker_all_actuals != nil && worker_all_plan != nil  %>

					<td><%= worker.name + " " + worker.surname %></td>

					<% if worker_all_actuals.time_in != nil  %>
						<td><%= worker_all_actuals.time_in.strftime('%H:%M:%S') + '/' + (worker_all_plan.time_in + (3600*12)).strftime('%H:%M:%S') %></td>
					<% else %>
						<td> <%= '- / ' + (worker_all_plan.time_in + (3600*12)).strftime('%H:%M:%S') %> </td>
					<% end %>

					<% if worker_all_actuals.time_out != nil %>
						<td><%= worker_all_actuals.time_out.strftime('%H:%M:%S') + '/' + (worker_all_plan.time_out+(3600*12)).strftime('%H:%M:%S')%></td>
					<% else %>
						<td> <%= '- / ' + (worker_all_plan.time_out+(3600*12)).strftime('%H:%M:%S') %></td>
					<% end %>

					<% if worker_all_actuals.OT != nil %>
						<td><%= worker_all_actuals.OT.to_s + '/' + worker_all_plan.OT.to_s %></td>
					<% else %>
						<td> <%= '- / ' + worker_all_plan.OT.to_s %></td>
					<% end %>

				<% else %>
					<% if worker_all_plan != nil %>
						<td><%= worker.name + " " + worker.surname %></td>
						<td> <%= '- / ' + (worker_all_plan.time_in + (3600*12)).strftime('%H:%M:%S') %></td>
						<td> <%= '- / ' + (worker_all_plan.time_out+(3600*12)).strftime('%H:%M:%S') %></td>
						<td> <%= '- / ' + worker_all_plan.OT.to_s %></td>

					<% end %>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

<script type="text/javascript">
	setTimeout("location.reload();",10000);
</script>

app/views/employees/show.html.erb
<body>
<h1> schedule ตารางงาน <%= current_user.name %> </h1>

<div class="table-container">
<%= form_tag schedule_path , :method => :get do %>
  <%= button_tag "Time in", :type => "save_in" , :name => "save_in" %>
  <%= button_tag "Time out", :type => "save_out" , :name => "save_out" %>
<% end %>

<table >
  <thead>
    <th> วันที่ </th>
    <th> เวลาเข้างาน </th>
    <th> เวลาออกงาน </th>
    <th> OT </th>
  </thead>
  <tbody>
    <% @all_plans.each do |plan| %>
      <tr>
        <% check_actual = Actual.find_by_plan_id(plan.id) %>
        <td><%= plan.date.strftime("%Y-%m-%d") %></td>
        <% if check_actual != nil %>
          <% if check_actual.time_in == nil %>
            <td><%= "- / " + (plan.time_in + (3600*12)).strftime("%H:%M:%S") %></td>
          <% else %>
            <td><%= check_actual.time_in.strftime("%H:%M:%S") + " / " + (plan.time_in + (3600*12)).strftime("%H:%M:%S") %></td>
          <% end %>
          <% if check_actual.time_out == nil %>
            <td><%= "- / " + (plan.time_out + (3600*12)).strftime("%H:%M:%S") %></td>
          <% else %>
            <td><%= check_actual.time_out.strftime("%H:%M:%S") + " / " + (plan.time_out + (3600*12)).strftime("%H:%M:%S") %></td>
          <% end %>
          <% if check_actual.OT == nil %>
            <td><%= "- / " + plan.OT.to_s %></td>
          <% else %>
            <td><%= check_actual.OT.to_s + " / " + plan.OT.to_s %></td>
          <% end %>
        <% else %>
          <% if plan != nil %>
            <td> <%= '- / ' + (plan.time_in + (3600*12)).strftime('%H:%M:%S') %></td>
            <td> <%= '- / ' + (plan.time_out + (3600*12)).strftime('%H:%M:%S') %></td>
            <td> <%= '- / ' + plan.OT.to_s %></td>
          <% else %>
            <td> - </td>
            <td> - </td>
            <td> - </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <img class="background" src="/assets/wave.png" width="500px">
  <div class="navbar">
        <div class="container">
            
            <% if logged_in? && current_user.position == "employee" %>
              <%= link_to 'Assight<span>Shift</span>'.html_safe, schedule_path, :class => "logo" %>
            <% else %>
              <%= link_to 'Assight<span>Shift</span>'.html_safe, root_path, :class => "logo" %>
            <% end %>

            <img id="mobile-cta" class="mobile-menu" src="/assets/menu.svg" alt="Open Navigation">
            <nav>
                <img id="mobile-exit" class="mobile-menu-exit" src="/assets/exit.svg" alt="Close Navigation">
                
                <ul class="primary-nav">
                    <li class="current">
                      <% if logged_in? && current_user.position == "employee" %>
                        <%= link_to 'Home', schedule_path%>
                      <% else %>
                        <%= link_to 'Home', root_path %>
                      <% end %>
                        
                    </li>
                </ul>

                <ul class="secondary-nav">
                    <li><% if logged_in? %><a>Welcome, <%= current_user.name %></a>
                    </li>
                    <li><%= link_to 'logout', logout_path,:class => "go-premium-cta" %><li>
                    <%else%>
                    <li><a>welcome</a></li>
                    <li class="go-premium-cta"><a href="#">Logout</a></li>
                    <%end%>
                </ul>
            </nav>
        </div>
    </div>

  <div id="main">
    <% if flash[:notice] %>
      <div class="message" id="notice">

        <%= flash[:notice] %>
      </div>
    <% elsif flash[:warning] %>
      <div class="message" id="warning">
        <%= flash[:warning] %>
      </div>
    <% end %>
    <%= yield %>
  
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script>

        const mobileBtn = document.getElementById('mobile-cta')
              nav = document.querySelector('nav')
              mobileBtnExit = document.getElementById('mobile-exit');

        mobileBtn.addEventListener('click', () => {
            nav.classList.add('menu-btn');
        })

        mobileBtnExit.addEventListener('click', () => {
            nav.classList.remove('menu-btn');
        })



    </script>
</body>

</html>